/** (c) Copyright by Yar.
 *
 * Source file generated automatically.
 */

import { Paradigms } from "../paradigm.js"

export default {
  "1": [[
    [{"case": "nominative", "gender": "masculine"}, "оди́н"],
    [{"case": "nominative", "gender": "feminine"}, "одна́"],
    [{"case": "nominative", "gender": "neuter"}, "одне́"],
    [{"case": "nominative", "gender": "neuter"}, "одно́"],
    [{"case": "genitive", "gender": "masculine"}, "одного́"],
    [{"case": "genitive", "gender": "feminine"}, "одніє́ї"],
    [{"case": "genitive", "gender": "feminine"}, "одно́ї"],
    [{"case": "genitive", "gender": "neuter"}, "одного́"],
    [{"case": "dative", "gender": "masculine"}, "одному́"],
    [{"case": "dative", "gender": "feminine"}, "одні́й"],
    [{"case": "dative", "gender": "neuter"}, "одному́"],
    [{"case": "accusative", "gender": "masculine", "animacy": "inanimate"}, "оди́н"],
    [{"case": "accusative", "gender": "masculine", "animacy": "animate"}, "одного́"],
    [{"case": "accusative", "gender": "feminine"}, "одну́"],
    [{"case": "accusative", "gender": "neuter"}, "одне́"],
    [{"case": "instrumental", "gender": "masculine"}, "одни́м"],
    [{"case": "instrumental", "gender": "feminine"}, "одніє́ю"],
    [{"case": "instrumental", "gender": "feminine"}, "одно́ю"],
    [{"case": "instrumental", "gender": "neuter"}, "одни́м"],
    [{"case": "locative", "gender": "masculine"}, "одному́"],
    [{"case": "locative", "gender": "masculine"}, "одні́м"],
    [{"case": "locative", "gender": "feminine"}, "одні́й"],
    [{"case": "locative", "gender": "neuter"}, "одному́"],
    [{"case": "locative", "gender": "neuter"}, "одні́м"],
    [{"case": "vocative", "gender": "masculine"}, "оди́н"],
    [{"case": "vocative", "gender": "feminine"}, "одна́"],
    [{"case": "vocative", "gender": "neuter"}, "одне́"],
  ], {}],
  "2": [[
    [{"case": "nominative", "gender": "masculine"}, "два́"],
    [{"case": "nominative", "gender": "feminine"}, "дві́"],
    [{"case": "nominative", "gender": "neuter"}, "два́"],
    [{"case": "genitive"}, "дво́х"],
    [{"case": "dative"}, "дво́м"],
    [{"case": "accusative", "gender": "masculine", "animacy": "inanimate"}, "два́"],
    [{"case": "accusative", "gender": "masculine", "animacy": "animate"}, "дво́х"],
    [{"case": "accusative", "gender": "feminine", "animacy": "inanimate"}, "дві́"],
    [{"case": "accusative", "gender": "feminine", "animacy": "animate"}, "дво́х"],
    [{"case": "accusative", "gender": "neuter", "animacy": "inanimate"}, "два́"],
    [{"case": "accusative", "gender": "neuter", "animacy": "animate"}, "дво́х"],
    [{"case": "instrumental"}, "двома́"],
    [{"case": "locative"}, "дво́х"],
    [{"case": "vocative", "gender": "masculine"}, "два́"],
    [{"case": "vocative", "gender": "feminine"}, "дві́"],
    [{"case": "vocative", "gender": "neuter"}, "два́"],
  ], {}],
  "3": [[
    [{"case": "nominative"}, "три́"],
    [{"case": "genitive"}, "трьо́х"],
    [{"case": "dative"}, "трьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "три́"],
    [{"case": "accusative", "animacy": "animate"}, "трьо́х"],
    [{"case": "instrumental"}, "трьома́"],
    [{"case": "locative"}, "трьо́х"],
    [{"case": "vocative"}, "три́"],
  ], {}],
  "4": [[
    [{"case": "nominative"}, "чоти́ри"],
    [{"case": "genitive"}, "чотирьо́х"],
    [{"case": "dative"}, "чотирьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "чоти́ри"],
    [{"case": "accusative", "animacy": "animate"}, "чотирьо́х"],
    [{"case": "instrumental"}, "чотирма́"],
    [{"case": "locative"}, "чотирьо́х"],
    [{"case": "vocative"}, "чоти́ри"],
  ], {}],
  "5": [[
    [{"case": "nominative"}, "пʼя́ть"],
    [{"case": "genitive"}, "пʼяти́"],
    [{"case": "genitive"}, "пʼятьо́х"],
    [{"case": "dative"}, "пʼяти́"],
    [{"case": "dative"}, "пʼятьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "пʼя́ть"],
    [{"case": "accusative", "animacy": "animate"}, "пʼятьо́х"],
    [{"case": "instrumental"}, "пʼятьма́"],
    [{"case": "instrumental"}, "пʼятьома́"],
    [{"case": "locative"}, "пʼяти́"],
    [{"case": "locative"}, "пʼятьо́х"],
    [{"case": "vocative"}, "пʼя́ть"],
  ], {}],
  "6": [[
    [{"case": "nominative"}, "ші́сть"],
    [{"case": "genitive"}, "шести́"],
    [{"case": "genitive"}, "шістьо́х"],
    [{"case": "dative"}, "шести́"],
    [{"case": "dative"}, "шістьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "ші́сть"],
    [{"case": "accusative", "animacy": "animate"}, "шістьо́х"],
    [{"case": "instrumental"}, "шістьма́"],
    [{"case": "instrumental"}, "шістьома́"],
    [{"case": "locative"}, "шести́"],
    [{"case": "locative"}, "шістьо́х"],
    [{"case": "vocative"}, "ші́сть"],
  ], {}],
  "7": [[
    [{"case": "nominative"}, "сі́м"],
    [{"case": "genitive"}, "семи́"],
    [{"case": "genitive"}, "сімо́х"],
    [{"case": "dative"}, "семи́"],
    [{"case": "dative"}, "сімо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "сі́м"],
    [{"case": "accusative", "animacy": "animate"}, "сімо́х"],
    [{"case": "instrumental"}, "сьома́"],
    [{"case": "instrumental"}, "сімома́"],
    [{"case": "locative"}, "семи́"],
    [{"case": "locative"}, "сімо́х"],
    [{"case": "vocative"}, "сі́м"],
  ], {}],
  "8": [[
    [{"case": "nominative"}, "ві́сім"],
    [{"case": "genitive"}, "восьми́"],
    [{"case": "genitive"}, "вісьмо́х"],
    [{"case": "dative"}, "восьми́"],
    [{"case": "dative"}, "вісьмо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "ві́сім"],
    [{"case": "accusative", "animacy": "animate"}, "вісьмо́х"],
    [{"case": "instrumental"}, "вісьма́"],
    [{"case": "instrumental"}, "вісьмома́"],
    [{"case": "locative"}, "восьми́"],
    [{"case": "locative"}, "вісьмо́х"],
    [{"case": "vocative"}, "ві́сім"],
  ], {}],
  "9": [[
    [{"case": "nominative"}, "де́вʼять"],
    [{"case": "genitive"}, "девʼяти́"],
    [{"case": "genitive"}, "девʼятьо́х"],
    [{"case": "dative"}, "девʼяти́"],
    [{"case": "dative"}, "девʼятьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "де́вʼять"],
    [{"case": "accusative", "animacy": "animate"}, "девʼятьо́х"],
    [{"case": "instrumental"}, "девʼятьма́"],
    [{"case": "instrumental"}, "девʼятьома́"],
    [{"case": "locative"}, "девʼяти́"],
    [{"case": "locative"}, "девʼятьо́х"],
    [{"case": "vocative"}, "де́вʼять"],
  ], {}],
  "10": [[
    [{"case": "nominative"}, "де́сять"],
    [{"case": "genitive"}, "десяти́"],
    [{"case": "genitive"}, "десятьо́х"],
    [{"case": "dative"}, "десяти́"],
    [{"case": "dative"}, "десятьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "де́сять"],
    [{"case": "accusative", "animacy": "animate"}, "десятьо́х"],
    [{"case": "instrumental"}, "десятьма́"],
    [{"case": "instrumental"}, "десятьома́"],
    [{"case": "locative"}, "десяти́"],
    [{"case": "locative"}, "десятьо́х"],
    [{"case": "vocative"}, "де́сять"],
  ], {}],
  "11": [[
    [{"case": "nominative"}, "одина́дцять"],
    [{"case": "genitive"}, "одинадцяти́"],
    [{"case": "genitive"}, "одинадцятьо́х"],
    [{"case": "dative"}, "одинадцяти́"],
    [{"case": "dative"}, "одинадцятьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "одина́дцять"],
    [{"case": "accusative", "animacy": "animate"}, "одинадцятьо́х"],
    [{"case": "instrumental"}, "одинадцятьма́"],
    [{"case": "instrumental"}, "одинадцятьома́"],
    [{"case": "locative"}, "одинадцяти́"],
    [{"case": "locative"}, "одинадцятьо́х"],
    [{"case": "vocative"}, "одина́дцять"],
  ], {}],
  "12": [[
    [{"case": "nominative"}, "двана́дцять"],
    [{"case": "genitive"}, "дванадцяти́"],
    [{"case": "genitive"}, "дванадцятьо́х"],
    [{"case": "dative"}, "дванадцяти́"],
    [{"case": "dative"}, "дванадцятьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "двана́дцять"],
    [{"case": "accusative", "animacy": "animate"}, "дванадцятьо́х"],
    [{"case": "instrumental"}, "дванадцятьма́"],
    [{"case": "instrumental"}, "дванадцятьома́"],
    [{"case": "locative"}, "дванадцяти́"],
    [{"case": "locative"}, "дванадцятьо́х"],
    [{"case": "vocative"}, "двана́дцять"],
  ], {}],
  "13": [[
    [{"case": "nominative"}, "трина́дцять"],
    [{"case": "genitive"}, "тринадцяти́"],
    [{"case": "genitive"}, "тринадцятьо́х"],
    [{"case": "dative"}, "тринадцяти́"],
    [{"case": "dative"}, "тринадцятьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "трина́дцять"],
    [{"case": "accusative", "animacy": "animate"}, "тринадцятьо́х"],
    [{"case": "instrumental"}, "тринадцятьма́"],
    [{"case": "instrumental"}, "тринадцятьома́"],
    [{"case": "locative"}, "тринадцяти́"],
    [{"case": "locative"}, "тринадцятьо́х"],
    [{"case": "vocative"}, "трина́дцять"],
  ], {}],
  "14": [[
    [{"case": "nominative"}, "чотирна́дцять"],
    [{"case": "genitive"}, "чотирнадцяти́"],
    [{"case": "genitive"}, "чотирнадцятьо́х"],
    [{"case": "dative"}, "чотирнадцяти́"],
    [{"case": "dative"}, "чотирнадцятьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "чотирна́дцять"],
    [{"case": "accusative", "animacy": "animate"}, "чотирнадцятьо́х"],
    [{"case": "instrumental"}, "чотирнадцятьма́"],
    [{"case": "instrumental"}, "чотирнадцятьома́"],
    [{"case": "locative"}, "чотирнадцяти́"],
    [{"case": "locative"}, "чотирнадцятьо́х"],
    [{"case": "vocative"}, "чотирна́дцять"],
  ], {}],
  "15": [[
    [{"case": "nominative"}, "пʼятна́дцять"],
    [{"case": "genitive"}, "пʼятнадцяти́"],
    [{"case": "genitive"}, "пʼятнадцятьо́х"],
    [{"case": "dative"}, "пʼятнадцяти́"],
    [{"case": "dative"}, "пʼятнадцятьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "пʼятна́дцять"],
    [{"case": "accusative", "animacy": "animate"}, "пʼятнадцятьо́х"],
    [{"case": "instrumental"}, "пʼятнадцятьма́"],
    [{"case": "instrumental"}, "пʼятнадцятьома́"],
    [{"case": "locative"}, "пʼятнадцяти́"],
    [{"case": "locative"}, "пʼятнадцятьо́х"],
    [{"case": "vocative"}, "пʼятна́дцять"],
  ], {}],
  "16": [[
    [{"case": "nominative"}, "шістна́дцять"],
    [{"case": "genitive"}, "шістнадцяти́"],
    [{"case": "genitive"}, "шістнадцятьо́х"],
    [{"case": "dative"}, "шістнадцяти́"],
    [{"case": "dative"}, "шістнадцятьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "шістна́дцять"],
    [{"case": "accusative", "animacy": "animate"}, "шістнадцятьо́х"],
    [{"case": "instrumental"}, "шістнадцятьма́"],
    [{"case": "instrumental"}, "шістнадцятьома́"],
    [{"case": "locative"}, "шістнадцяти́"],
    [{"case": "locative"}, "шістнадцятьо́х"],
    [{"case": "vocative"}, "шістна́дцять"],
  ], {}],
  "17": [[
    [{"case": "nominative"}, "сімна́дцять"],
    [{"case": "genitive"}, "сімнадцяти́"],
    [{"case": "genitive"}, "сімнадцятьо́х"],
    [{"case": "dative"}, "сімнадцяти́"],
    [{"case": "dative"}, "сімнадцятьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "сімна́дцять"],
    [{"case": "accusative", "animacy": "animate"}, "сімнадцятьо́х"],
    [{"case": "instrumental"}, "сімнадцятьма́"],
    [{"case": "instrumental"}, "сімнадцятьома́"],
    [{"case": "locative"}, "сімнадцяти́"],
    [{"case": "locative"}, "сімнадцятьо́х"],
    [{"case": "vocative"}, "сімна́дцять"],
  ], {}],
  "18": [[
    [{"case": "nominative"}, "вісімна́дцять"],
    [{"case": "genitive"}, "вісімнадцяти́"],
    [{"case": "genitive"}, "вісімнадцятьо́х"],
    [{"case": "dative"}, "вісімнадцяти́"],
    [{"case": "dative"}, "вісімнадцятьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "вісімна́дцять"],
    [{"case": "accusative", "animacy": "animate"}, "вісімнадцятьо́х"],
    [{"case": "instrumental"}, "вісімнадцятьма́"],
    [{"case": "instrumental"}, "вісімнадцятьома́"],
    [{"case": "locative"}, "вісімнадцяти́"],
    [{"case": "locative"}, "вісімнадцятьо́х"],
    [{"case": "vocative"}, "вісімна́дцять"],
  ], {}],
  "19": [[
    [{"case": "nominative"}, "девʼятна́дцять"],
    [{"case": "genitive"}, "девʼятнадцяти́"],
    [{"case": "genitive"}, "девʼятнадцятьо́х"],
    [{"case": "dative"}, "девʼятнадцяти́"],
    [{"case": "dative"}, "девʼятнадцятьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "девʼятна́дцять"],
    [{"case": "accusative", "animacy": "animate"}, "девʼятнадцятьо́х"],
    [{"case": "instrumental"}, "девʼятнадцятьма́"],
    [{"case": "instrumental"}, "девʼятнадцятьома́"],
    [{"case": "locative"}, "девʼятнадцяти́"],
    [{"case": "locative"}, "девʼятнадцятьо́х"],
    [{"case": "vocative"}, "девʼятна́дцять"],
  ], {}],
  "20": [[
    [{"case": "nominative"}, "два́дцять"],
    [{"case": "genitive"}, "двадцяти́"],
    [{"case": "genitive"}, "двадцятьо́х"],
    [{"case": "dative"}, "двадцяти́"],
    [{"case": "dative"}, "двадцятьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "два́дцять"],
    [{"case": "accusative", "animacy": "animate"}, "двадцятьо́х"],
    [{"case": "instrumental"}, "двадцятьма́"],
    [{"case": "instrumental"}, "двадцятьома́"],
    [{"case": "locative"}, "двадцяти́"],
    [{"case": "locative"}, "двадцятьо́х"],
    [{"case": "vocative"}, "два́дцять"],
  ], {}],
  "30": [[
    [{"case": "nominative"}, "три́дцять"],
    [{"case": "genitive"}, "тридцяти́"],
    [{"case": "genitive"}, "тридцятьо́х"],
    [{"case": "dative"}, "тридцяти́"],
    [{"case": "dative"}, "тридцятьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "три́дцять"],
    [{"case": "accusative", "animacy": "animate"}, "тридцятьо́х"],
    [{"case": "instrumental"}, "тридцятьма́"],
    [{"case": "instrumental"}, "тридцятьома́"],
    [{"case": "locative"}, "тридцяти́"],
    [{"case": "locative"}, "тридцятьо́х"],
    [{"case": "vocative"}, "три́дцять"],
  ], {}],
  "40": [[
    [{"case": "nominative"}, "со́рок"],
    [{"case": "genitive"}, "сорока́"],
    [{"case": "dative"}, "сорока́"],
    [{"case": "accusative"}, "со́рок"],
    [{"case": "instrumental"}, "сорока́"],
    [{"case": "locative"}, "сорока́"],
    [{"case": "vocative"}, "со́рок"],
  ], {}],
  "50": [[
    [{"case": "nominative"}, "пʼятдеся́т"],
    [{"case": "genitive"}, "пʼятдесяти́"],
    [{"case": "genitive"}, "пʼятдесятьо́х"],
    [{"case": "dative"}, "пʼятдесяти́"],
    [{"case": "dative"}, "пʼятдесятьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "пʼятдеся́т"],
    [{"case": "accusative", "animacy": "animate"}, "пʼятдесятьо́х"],
    [{"case": "instrumental"}, "пʼятдесятьма́"],
    [{"case": "instrumental"}, "пʼятдесятьома́"],
    [{"case": "locative"}, "пʼятдесяти́"],
    [{"case": "locative"}, "пʼятдесятьо́х"],
    [{"case": "vocative"}, "пʼятдеся́т"],
  ], {}],
  "60": [[
    [{"case": "nominative"}, "шістдеся́т"],
    [{"case": "genitive"}, "шістдесяти́"],
    [{"case": "genitive"}, "шістдесятьо́х"],
    [{"case": "dative"}, "шістдесяти́"],
    [{"case": "dative"}, "шістдесятьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "шістдеся́т"],
    [{"case": "accusative", "animacy": "animate"}, "шістдесятьо́х"],
    [{"case": "instrumental"}, "шістдесятьма́"],
    [{"case": "instrumental"}, "шістдесятьома́"],
    [{"case": "locative"}, "шістдесяти́"],
    [{"case": "locative"}, "шістдесятьо́х"],
    [{"case": "vocative"}, "шістдеся́т"],
  ], {}],
  "70": [[
    [{"case": "nominative"}, "сімдеся́т"],
    [{"case": "genitive"}, "сімдесяти́"],
    [{"case": "genitive"}, "сімдесятьо́х"],
    [{"case": "dative"}, "сімдесяти́"],
    [{"case": "dative"}, "сімдесятьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "сімдеся́т"],
    [{"case": "accusative", "animacy": "animate"}, "сімдесятьо́х"],
    [{"case": "instrumental"}, "сімдесятьма́"],
    [{"case": "instrumental"}, "сімдесятьома́"],
    [{"case": "locative"}, "сімдесяти́"],
    [{"case": "locative"}, "сімдесятьо́х"],
    [{"case": "vocative"}, "сімдеся́т"],
  ], {}],
  "80": [[
    [{"case": "nominative"}, "вісімдеся́т"],
    [{"case": "genitive"}, "вісімдесяти́"],
    [{"case": "genitive"}, "вісімдесятьо́х"],
    [{"case": "dative"}, "вісімдесяти́"],
    [{"case": "dative"}, "вісімдесятьо́м"],
    [{"case": "accusative", "animacy": "inanimate"}, "вісімдеся́т"],
    [{"case": "accusative", "animacy": "animate"}, "вісімдесятьо́х"],
    [{"case": "instrumental"}, "вісімдесятьма́"],
    [{"case": "instrumental"}, "вісімдесятьома́"],
    [{"case": "locative"}, "вісімдесяти́"],
    [{"case": "locative"}, "вісімдесятьо́х"],
    [{"case": "vocative"}, "вісімдеся́т"],
  ], {}],
  "90": [[
    [{"case": "nominative"}, "девʼяно́сто"],
    [{"case": "genitive"}, "девʼяно́ста"],
    [{"case": "dative"}, "девʼяно́ста"],
    [{"case": "accusative"}, "девʼяно́сто"],
    [{"case": "instrumental"}, "девʼяно́ста"],
    [{"case": "locative"}, "девʼяно́ста"],
    [{"case": "vocative"}, "девʼяно́сто"],
  ], {}],
  "100": [[
    [{"case": "nominative"}, "сто́"],
    [{"case": "genitive"}, "ста́"],
    [{"case": "dative"}, "ста́"],
    [{"case": "accusative"}, "сто́"],
    [{"case": "instrumental"}, "ста́"],
    [{"case": "locative"}, "ста́"],
    [{"case": "vocative"}, "сто́"],
  ], {}],
  "200": [[
    [{"case": "nominative"}, "дві́сті"],
    [{"case": "genitive"}, "двохсо́т"],
    [{"case": "dative"}, "двомста́м"],
    [{"case": "accusative"}, "дві́сті"],
    [{"case": "instrumental"}, "двомаста́ми"],
    [{"case": "locative"}, "двохста́х"],
    [{"case": "vocative"}, "дві́сті"],
  ], {}],
  "300": [[
    [{"case": "nominative"}, "три́ста"],
    [{"case": "genitive"}, "трьохсо́т"],
    [{"case": "dative"}, "трьомста́м"],
    [{"case": "accusative"}, "три́ста"],
    [{"case": "instrumental"}, "трьомаста́ми"],
    [{"case": "locative"}, "трьохста́х"],
    [{"case": "vocative"}, "три́ста"],
  ], {}],
  "400": [[
    [{"case": "nominative"}, "чоти́риста"],
    [{"case": "genitive"}, "чотирьохсо́т"],
    [{"case": "dative"}, "чотирьомста́м"],
    [{"case": "accusative"}, "чоти́риста"],
    [{"case": "instrumental"}, "чотирмаста́ми"],
    [{"case": "locative"}, "чотирьохста́х"],
    [{"case": "vocative"}, "чоти́риста"],
  ], {}],
  "500": [[
    [{"case": "nominative"}, "пʼятсо́т"],
    [{"case": "genitive"}, "пʼятисо́т"],
    [{"case": "dative"}, "пʼятиста́м"],
    [{"case": "accusative"}, "пʼятсо́т"],
    [{"case": "instrumental"}, "пʼятьмаста́ми"],
    [{"case": "instrumental"}, "пʼятьомаста́ми"],
    [{"case": "locative"}, "пʼятиста́х"],
    [{"case": "vocative"}, "пʼятсо́т"],
  ], {}],
  "600": [[
    [{"case": "nominative"}, "шістсо́т"],
    [{"case": "genitive"}, "шестисо́т"],
    [{"case": "dative"}, "шестиста́м"],
    [{"case": "accusative"}, "шістсо́т"],
    [{"case": "instrumental"}, "шістьмаста́ми"],
    [{"case": "instrumental"}, "шістьомаста́ми"],
    [{"case": "locative"}, "шестиста́х"],
    [{"case": "vocative"}, "шістсо́т"],
  ], {}],
  "700": [[
    [{"case": "nominative"}, "сімсо́т"],
    [{"case": "genitive"}, "семисо́т"],
    [{"case": "dative"}, "семиста́м"],
    [{"case": "accusative"}, "сімсо́т"],
    [{"case": "instrumental"}, "семиста́ми"],
    [{"case": "instrumental"}, "сімомаста́ми"],
    [{"case": "locative"}, "семиста́х"],
    [{"case": "vocative"}, "сімсо́т"],
  ], {}],
  "800": [[
    [{"case": "nominative"}, "вісімсо́т"],
    [{"case": "genitive"}, "восьмисо́т"],
    [{"case": "dative"}, "восьмиста́м"],
    [{"case": "accusative"}, "вісімсо́т"],
    [{"case": "instrumental"}, "вісьмаста́ми"],
    [{"case": "instrumental"}, "вісьмомаста́ми"],
    [{"case": "locative"}, "восьмиста́х"],
    [{"case": "vocative"}, "вісімсо́т"],
  ], {}],
  "900": [[
    [{"case": "nominative"}, "девʼятсо́т"],
    [{"case": "genitive"}, "девʼятисо́т"],
    [{"case": "dative"}, "девʼятиста́м"],
    [{"case": "accusative"}, "девʼятсо́т"],
    [{"case": "instrumental"}, "девʼятьмаста́ми"],
    [{"case": "instrumental"}, "девʼятьомаста́ми"],
    [{"case": "locative"}, "девʼятиста́х"],
    [{"case": "vocative"}, "девʼятсо́т"],
  ], {}],
  "0": [[
    [{"case": "nominative", "number": "singular"}, "ну́ль"],
    [{"case": "genitive", "number": "singular"}, "нуля́"],
    [{"case": "dative", "number": "singular"}, "нулю́"],
    [{"case": "dative", "number": "singular"}, "нуле́ві"],
    [{"case": "accusative", "number": "singular"}, "ну́ль"],
    [{"case": "instrumental", "number": "singular"}, "нуле́м"],
    [{"case": "locative", "number": "singular"}, "нулі́"],
    [{"case": "locative", "number": "singular"}, "нулю́"],
    [{"case": "vocative", "number": "singular"}, "ну́лю"],
    [{"case": "nominative", "number": "plural"}, "нулі́"],
    [{"case": "genitive", "number": "plural"}, "нулі́в"],
    [{"case": "dative", "number": "plural"}, "нуля́м"],
    [{"case": "accusative", "number": "plural"}, "нулі́"],
    [{"case": "instrumental", "number": "plural"}, "нуля́ми"],
    [{"case": "locative", "number": "plural"}, "нуля́х"],
    [{"case": "vocative", "number": "plural"}, "нулі́"],
  ], {"gender": "masculine", "animacy": "inanimate"}],
  "1000": [[
    [{"case": "nominative", "number": "singular"}, "ти́сяча"],
    [{"case": "nominative", "number": "plural"}, "ти́сячі"],
    [{"case": "genitive", "number": "singular"}, "ти́сячі"],
    [{"case": "genitive", "number": "plural"}, "ти́сяч"],
    [{"case": "dative", "number": "singular"}, "ти́сячі"],
    [{"case": "dative", "number": "plural"}, "ти́сячам"],
    [{"case": "accusative", "number": "singular"}, "ти́сячу"],
    [{"case": "accusative", "number": "plural"}, "ти́сячі"],
    [{"case": "instrumental", "number": "singular"}, "ти́сячею"],
    [{"case": "instrumental", "number": "plural"}, "ти́сячами"],
    [{"case": "locative", "number": "singular"}, "ти́сячі"],
    [{"case": "locative", "number": "plural"}, "ти́сячах"],
    [{"case": "vocative", "number": "singular"}, "ти́сяче"],
    [{"case": "vocative", "number": "plural"}, "ти́сячі"],
  ], {"gender": "feminine", "animacy": "inanimate"}],
  "1000000": [[
    [{"case": "nominative", "number": "singular"}, "мільйо́н"],
    [{"case": "nominative", "number": "plural"}, "мільйо́ни"],
    [{"case": "genitive", "number": "singular"}, "мільйо́на"],
    [{"case": "genitive", "number": "plural"}, "мільйо́нів"],
    [{"case": "dative", "number": "singular"}, "мільйо́ну"],
    [{"case": "dative", "number": "singular"}, "мільйо́нові"],
    [{"case": "dative", "number": "plural"}, "мільйо́нам"],
    [{"case": "accusative", "number": "singular"}, "мільйо́н"],
    [{"case": "accusative", "number": "plural"}, "мільйо́ни"],
    [{"case": "instrumental", "number": "singular"}, "мільйо́ном"],
    [{"case": "instrumental", "number": "plural"}, "мільйо́нами"],
    [{"case": "locative", "number": "singular"}, "мільйо́ні"],
    [{"case": "locative", "number": "plural"}, "мільйо́нах"],
    [{"case": "vocative", "number": "singular"}, "мільйо́не"],
    [{"case": "vocative", "number": "plural"}, "мільйо́ни"],
  ], {"gender": "masculine", "animacy": "inanimate"}],
  "1000000000": [[
    [{"case": "nominative", "number": "singular"}, "мілья́рд"],
    [{"case": "nominative", "number": "plural"}, "мілья́рди"],
    [{"case": "genitive", "number": "singular"}, "мілья́рда"],
    [{"case": "genitive", "number": "plural"}, "мілья́рдів"],
    [{"case": "dative", "number": "singular"}, "мілья́рду"],
    [{"case": "dative", "number": "singular"}, "мілья́рдові"],
    [{"case": "dative", "number": "plural"}, "мілья́рдам"],
    [{"case": "accusative", "number": "singular"}, "мілья́рд"],
    [{"case": "accusative", "number": "plural"}, "мілья́рди"],
    [{"case": "instrumental", "number": "singular"}, "мілья́рдом"],
    [{"case": "instrumental", "number": "plural"}, "мілья́рдами"],
    [{"case": "locative", "number": "singular"}, "мілья́рді"],
    [{"case": "locative", "number": "plural"}, "мілья́рдах"],
    [{"case": "vocative", "number": "singular"}, "мілья́рде"],
    [{"case": "vocative", "number": "plural"}, "мілья́рди"],
  ], {"gender": "masculine", "animacy": "inanimate"}],
  "1000000000000": [[
    [{"case": "nominative", "number": "singular"}, "трильйо́н"],
    [{"case": "nominative", "number": "plural"}, "трильйо́ни"],
    [{"case": "genitive", "number": "singular"}, "трильйо́на"],
    [{"case": "genitive", "number": "plural"}, "трильйо́нів"],
    [{"case": "dative", "number": "singular"}, "трильйо́ну"],
    [{"case": "dative", "number": "singular"}, "трильйо́нові"],
    [{"case": "dative", "number": "plural"}, "трильйо́нам"],
    [{"case": "accusative", "number": "singular"}, "трильйо́н"],
    [{"case": "accusative", "number": "plural"}, "трильйо́ни"],
    [{"case": "instrumental", "number": "singular"}, "трильйо́ном"],
    [{"case": "instrumental", "number": "plural"}, "трильйо́нами"],
    [{"case": "locative", "number": "singular"}, "трильйо́ні"],
    [{"case": "locative", "number": "plural"}, "трильйо́нах"],
    [{"case": "vocative", "number": "singular"}, "трильйо́не"],
    [{"case": "vocative", "number": "plural"}, "трильйо́ни"],
  ], {"gender": "masculine", "animacy": "inanimate"}],
  "1000000000000000": [[
    [{"case": "nominative", "number": "singular"}, "квадрильйо́н"],
    [{"case": "nominative", "number": "plural"}, "квадрильйо́ни"],
    [{"case": "genitive", "number": "singular"}, "квадрильйо́на"],
    [{"case": "genitive", "number": "plural"}, "квадрильйо́нів"],
    [{"case": "dative", "number": "singular"}, "квадрильйо́ну"],
    [{"case": "dative", "number": "singular"}, "квадрильйо́нові"],
    [{"case": "dative", "number": "plural"}, "квадрильйо́нам"],
    [{"case": "accusative", "number": "singular"}, "квадрильйо́н"],
    [{"case": "accusative", "number": "plural"}, "квадрильйо́ни"],
    [{"case": "instrumental", "number": "singular"}, "квадрильйо́ном"],
    [{"case": "instrumental", "number": "plural"}, "квадрильйо́нами"],
    [{"case": "locative", "number": "singular"}, "квадрильйо́ні"],
    [{"case": "locative", "number": "plural"}, "квадрильйо́нах"],
    [{"case": "vocative", "number": "singular"}, "квадрильйо́не"],
    [{"case": "vocative", "number": "plural"}, "квадрильйо́ни"],
  ], {"gender": "masculine", "animacy": "inanimate"}],
  "1000000000000000000": [[
    [{"case": "nominative", "number": "singular"}, "квінтильйо́н"],
    [{"case": "nominative", "number": "plural"}, "квінтильйо́ни"],
    [{"case": "genitive", "number": "singular"}, "квінтильйо́на"],
    [{"case": "genitive", "number": "plural"}, "квінтильйо́нів"],
    [{"case": "dative", "number": "singular"}, "квінтильйо́ну"],
    [{"case": "dative", "number": "singular"}, "квінтильйо́нові"],
    [{"case": "dative", "number": "plural"}, "квінтильйо́нам"],
    [{"case": "accusative", "number": "singular"}, "квінтильйо́н"],
    [{"case": "accusative", "number": "plural"}, "квінтильйо́ни"],
    [{"case": "instrumental", "number": "singular"}, "квінтильйо́ном"],
    [{"case": "instrumental", "number": "plural"}, "квінтильйо́нами"],
    [{"case": "locative", "number": "singular"}, "квінтильйо́ні"],
    [{"case": "locative", "number": "plural"}, "квінтильйо́нах"],
    [{"case": "vocative", "number": "singular"}, "квінтильйо́не"],
    [{"case": "vocative", "number": "plural"}, "квінтильйо́ни"],
  ], {"gender": "masculine", "animacy": "inanimate"}],
  "1000000000000000000000": [[
    [{"case": "nominative", "number": "singular"}, "секстильйо́н"],
    [{"case": "nominative", "number": "plural"}, "секстильйо́ни"],
    [{"case": "genitive", "number": "singular"}, "секстильйо́на"],
    [{"case": "genitive", "number": "plural"}, "секстильйо́нів"],
    [{"case": "dative", "number": "singular"}, "секстильйо́ну"],
    [{"case": "dative", "number": "singular"}, "секстильйо́нові"],
    [{"case": "dative", "number": "plural"}, "секстильйо́нам"],
    [{"case": "accusative", "number": "singular"}, "секстильйо́н"],
    [{"case": "accusative", "number": "plural"}, "секстильйо́ни"],
    [{"case": "instrumental", "number": "singular"}, "секстильйо́ном"],
    [{"case": "instrumental", "number": "plural"}, "секстильйо́нами"],
    [{"case": "locative", "number": "singular"}, "секстильйо́ні"],
    [{"case": "locative", "number": "plural"}, "секстильйо́нах"],
    [{"case": "vocative", "number": "singular"}, "секстильйо́не"],
    [{"case": "vocative", "number": "plural"}, "секстильйо́ни"],
  ], {"gender": "masculine", "animacy": "inanimate"}],
  "1000000000000000000000000": [[
    [{"case": "nominative", "number": "singular"}, "септильйо́н"],
    [{"case": "nominative", "number": "plural"}, "септильйо́ни"],
    [{"case": "genitive", "number": "singular"}, "септильйо́на"],
    [{"case": "genitive", "number": "plural"}, "септильйо́нів"],
    [{"case": "dative", "number": "singular"}, "септильйо́ну"],
    [{"case": "dative", "number": "singular"}, "септильйо́нові"],
    [{"case": "dative", "number": "plural"}, "септильйо́нам"],
    [{"case": "accusative", "number": "singular"}, "септильйо́н"],
    [{"case": "accusative", "number": "plural"}, "септильйо́ни"],
    [{"case": "instrumental", "number": "singular"}, "септильйо́ном"],
    [{"case": "instrumental", "number": "plural"}, "септильйо́нами"],
    [{"case": "locative", "number": "singular"}, "септильйо́ні"],
    [{"case": "locative", "number": "plural"}, "септильйо́нах"],
    [{"case": "vocative", "number": "singular"}, "септильйо́не"],
    [{"case": "vocative", "number": "plural"}, "септильйо́ни"],
  ], {"gender": "masculine", "animacy": "inanimate"}],
} as Paradigms
